taxonomies: false
title: Default
sections:
  main:
    display: 'Page Content'
    fields:
      header_image:
        container: main
        folder: img
        restrict: true
        max_files: 1
        mode: grid
        type: assets
        display: 'Header Image'
      body:
        type: replicator
        display: Body
        sets:
          text:
            display: Text
            fields:
              content:
                type: redactor
                display: Content
                settings: Standard
                container: main
                folder: img
              columns:
                type: radio
                display: Column
                options:
                  left: Left
                  right: Right
                  full: Full
                width: 50
                default: full
                inline: true
                instructions: 'Should this be full width or share the row with another element?'
              proportion:
                options:
                  na: 'Doesn''t Apply'
                  fifty: 50%
                  seventy-five: 75%
                inline: true
                type: radio
                width: 50
                display: Proportion
                default: na
                instructions: 'Applies only if Column is left or right.'
          subheadline:
            display: Subheadline
            fields:
              subheadline_text:
                type: text
                display: 'Subheadline Text'
                width: 75
              center:
                type: toggle
                display: Center
                width: 25
          image:
            display: Image
            fields:
              inline_image:
                type: assets
                display: 'Inline Image'
                container: main
                folder: img
                restrict: true
                max_files: 1
                width: 33
              alignment:
                type: radio
                display: Alignment
                options:
                  left: Left
                  right: Right
                  center: Center
                width: 33
                default: center
              proportion:
                options:
                  full: Full
                  fifty: 50%
                  twenty-five: 25%
                inline: false
                type: radio
                width: 33
                display: Proportion
                default: full
          quote:
            display: Quote
            fields:
              quote:
                type: textarea
                display: 'Quote Text'
                width: 50
              attribution:
                type: text
                display: Attribution
                width: 50
          table:
            display: Table
            fields:
              table:
                type: table
                display: Table
          accordion:
            display: Accordion
            fields:
              accordion_header:
                type: text
                display: 'Accordion Section Header'
              accordion:
                sets:
                  accordion:
                    display: Accordion
                    fields:
                      accordion_title:
                        type: text
                        display: 'Accordion Title'
                      accordion_text:
                        settings: Standard
                        container: main
                        folder: img
                        restrict_assets: true
                        type: redactor
                        display: 'Accordion Text'
                type: replicator
                display: Accordion
          grid:
            display: Grid
            fields:
              columns:
                type: text
                width: 75
                display: 'Number of items per row'
              border:
                type: toggle
                width: 25
                display: Border
              block_grid:
                sets:
                  block_grid:
                    display: 'Block Grid'
                    fields:
                      content:
                        settings: Standard
                        container: main
                        folder: img
                        restrict_assets: true
                        type: redactor
                        display: Content
                type: replicator
                display: 'Block Grid'
  seo:
    display: SEO
    fields: {  }
  sidebar:
    display: Sidebar
    fields:
      slug:
        display: Slug
        type: text
