routes:
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
collections:
  locations: '/collections/{slug}'
  news: '/news/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
